#!/bin/bash
# =============================================================================
# Apple Mail Signature Deployer
# Generated by MailSign — {{ server_url }}
#
# Benötigt: curl, PlistBuddy, sqlite3, base64, osascript
# Alle Werkzeuge sind in macOS eingebaut — kein CLT, kein Python nötig.
# =============================================================================
set -uo pipefail

SERVER_URL="{{ server_url }}"
API_KEY="{{ api_key }}"
PLISTBUDDY="/usr/libexec/PlistBuddy"
FORCE_EMAIL=""

# Optionaler Parameter -e email@domain.com (für manuellen Test ohne Jamf)
while getopts "e:" opt 2>/dev/null; do
    case $opt in e) FORCE_EMAIL="$OPTARG" ;; esac
done

LOGFILE="/tmp/sigdeploy_$(date +%Y%m%d_%H%M%S).log"
log() { echo "[SigDeploy] $*" | tee -a "$LOGFILE" >&2; }
run_as=""   # wird nach User-Ermittlung gesetzt
ACCT_ID_MAP=""  # email|uuid Paare, befüllt von build_acct_id_map()

# ---- Benutzer ermitteln -----------------------------------------------------
if [ "$(id -u)" -eq 0 ]; then
    CURRENT_USER=$(stat -f "%Su" /dev/console 2>/dev/null || true)
    if [ -z "$CURRENT_USER" ] || [ "$CURRENT_USER" = "root" ]; then
        log "Kein Benutzer eingeloggt — abbruch."
        exit 0
    fi
else
    CURRENT_USER=$(id -un)
fi

USER_HOME=$(dscl . -read /Users/"$CURRENT_USER" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
[ -z "$USER_HOME" ] && USER_HOME="/Users/$CURRENT_USER"
[ "$(id -u)" -eq 0 ] && run_as="sudo -u $CURRENT_USER" || run_as=""
log "Benutzer: $CURRENT_USER  Home: $USER_HOME"

# ---- Signaturen-Verzeichnis suchen ------------------------------------------
# Container-Pfad (Sonoma/Sequoia) hat Vorrang vor klassischem Pfad (< Sonoma)
SIG_DIR=""
for v in V10 V9 V8 V7 V6; do
    for base in \
        "$USER_HOME/Library/Containers/com.apple.mail/Data/Library/Mail/$v/MailData" \
        "$USER_HOME/Library/Mail/$v/MailData"; do
        if [ -d "$base" ]; then
            SIG_DIR="$base/Signatures"
            log "Mail $v gefunden: $base"
            break 2
        fi
    done
done

if [ -z "$SIG_DIR" ]; then
    log "FEHLER: Mail-Datenverzeichnis nicht gefunden."
    exit 1
fi

$run_as mkdir -p "$SIG_DIR"

# ---- Mail-Accounts ermitteln ------------------------------------------------
get_accounts() {
    local found=""

    # Methode 1: AppleScript — direkt Mail befragen (kein FDA nötig)
    if ! pgrep -xq "Mail" 2>/dev/null; then
        log "  Mail wird kurz gestartet um Accounts abzufragen..."
        $run_as open -a Mail
        local waited=0
        while ! pgrep -xq "Mail" 2>/dev/null && [ $waited -lt 20 ]; do
            sleep 1; waited=$((waited + 1))
        done
        sleep 5
    fi

    local as_result
    as_result=$($run_as osascript 2>/dev/null << 'ASEOF'
tell application "Mail"
    set out to ""
    repeat with a in accounts
        set addrs to email addresses of a
        if class of addrs is string then
            set out to out & addrs & linefeed
        else
            repeat with addr in addrs
                set out to out & addr & linefeed
            end repeat
        end if
    end repeat
    return out
end tell
ASEOF
    )
    if [ -n "$as_result" ]; then
        found="$found
$as_result"
        log "  Accounts via AppleScript gefunden"
    else
        log "  AppleScript: keine Antwort (PPPC-Profil deployed? Mail geöffnet?)"
    fi

    # Account-Ordner liegen eine Ebene über dem MailData-Verzeichnis (V10-Ebene)
    local mail_ver_dir
    mail_ver_dir="$(dirname "$(dirname "$SIG_DIR")")"

    # Methode 2a: Alte Ordnernamen "IMAP-user@domain.com"
    while IFS= read -r dir; do
        local base
        base=$(basename "$dir")
        if [[ "$base" == *"-"*"@"* ]]; then
            found="$found
$(echo "${base#*-}" | tr '[:upper:]' '[:lower:]')"
        fi
    done < <(find "$mail_ver_dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

    # Methode 2b: UUID-Ordner — Email steht in Plist drin
    while IFS= read -r dir; do
        local base
        base=$(basename "$dir")
        if [[ "$base" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]]; then
            while IFS= read -r plist; do
                local email=""
                email=$("$PLISTBUDDY" -c "Print :AccountEmail" "$plist" 2>/dev/null || true)
                [ -z "$email" ] && email=$("$PLISTBUDDY" -c "Print :Email"    "$plist" 2>/dev/null || true)
                [ -z "$email" ] && email=$("$PLISTBUDDY" -c "Print :username" "$plist" 2>/dev/null || true)
                [[ "$email" == *"@"* ]] && found="$found
$(echo "$email" | tr '[:upper:]' '[:lower:]')"
            done < <(find "$dir" -maxdepth 2 -name "*.plist" 2>/dev/null)
        fi
    done < <(find "$mail_ver_dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

    # Methode 3: Accounts4.db
    local db="$USER_HOME/Library/Accounts/Accounts4.db"
    if [ -f "$db" ]; then
        while IFS= read -r email; do
            [ -n "$email" ] && found="$found
$email"
        done < <(sqlite3 "$db" \
            "SELECT lower(ZUSERNAME) FROM ZACCOUNT WHERE ZUSERNAME LIKE '%@%'" \
            2>/dev/null || true)
    fi

    echo "$found" | sort -u | grep -v '^[[:space:]]*$' | grep "@"
}

# ---- Signatur-Datei schreiben + AllSignatures.plist aktualisieren -----------
write_signature_file() {
    local sig_uuid="$1"
    local sig_name="$2"
    local mime_file="$3"

    local sig_file="$SIG_DIR/${sig_uuid}.mailsignature"
    cp "$mime_file" "$sig_file"
    [ "$(id -u)" -eq 0 ] && chown "$CURRENT_USER" "$sig_file"
    chmod 600 "$sig_file"

    local plist="$SIG_DIR/AllSignatures.plist"
    if [ ! -f "$plist" ]; then
        $run_as "$PLISTBUDDY" -c "Add : array" "$plist" 2>/dev/null || true
    fi

    # Bestehenden Eintrag mit gleicher UUID entfernen
    local count idx
    count=$($run_as "$PLISTBUDDY" -c "Print" "$plist" 2>/dev/null | grep -c "SignatureUniqueId" || echo 0)
    for idx in $(seq $((count - 1)) -1 0); do
        local uid
        uid=$($run_as "$PLISTBUDDY" -c "Print :${idx}:SignatureUniqueId" "$plist" 2>/dev/null || echo "")
        [ "$uid" = "$sig_uuid" ] && $run_as "$PLISTBUDDY" -c "Delete :${idx}" "$plist" 2>/dev/null || true
    done

    $run_as "$PLISTBUDDY" -c "Add :0 dict"                              "$plist" 2>/dev/null
    $run_as "$PLISTBUDDY" -c "Add :0:SignatureIsRich bool true"          "$plist" 2>/dev/null
    $run_as "$PLISTBUDDY" -c "Add :0:SignatureName string $sig_name"     "$plist" 2>/dev/null
    $run_as "$PLISTBUDDY" -c "Add :0:SignatureUniqueId string $sig_uuid" "$plist" 2>/dev/null

    log "  Datei: ${sig_uuid}.mailsignature  Name: $sig_name"
}

# ---- Account-Bindung via AppleScript (mit Polling-Loop) ---------------------
bind_account() {
    local account_email="$1"
    local sig_name="$2"
    local sig_uuid="$3"

    log "  Zuweisen: $account_email → '$sig_name'"

    local tmp_out tmp_err
    tmp_out=$(mktemp /tmp/sigout_XXXXXX)
    tmp_err=$(mktemp /tmp/sigerr_XXXXXX)
    chmod a+r "$tmp_out" "$tmp_err" 2>/dev/null || true

    # Wartet bis zu 60 Sekunden bis Mail die Signatur geladen hat, dann bindet.
    $run_as osascript > "$tmp_out" 2>"$tmp_err" << ASEOF
tell application "Mail"
    set targetName to "$sig_name"
    set targetEmail to "$account_email"

    -- Auf Signatur warten (max. 60 Sekunden in 2s-Schritten)
    set foundSig to missing value
    set waited to 0
    repeat while foundSig is missing value and waited < 60
        repeat with s in (every signature)
            if name of s is targetName then
                set foundSig to s
                exit repeat
            end if
        end repeat
        if foundSig is missing value then
            delay 2
            set waited to waited + 2
        end if
    end repeat

    if foundSig is missing value then
        set allNames to {}
        repeat with s in (every signature)
            set end of allNames to name of s
        end repeat
        return "SIG_NOT_FOUND – geladen: " & (allNames as text)
    end if

    -- Passenden Account suchen und Signatur setzen
    set bound to false
    repeat with acct in accounts
        set addrs to email addresses of acct
        if class of addrs is string then
            if (addrs as string) is targetEmail then
                tell acct to set default message signature to foundSig
                set bound to true
            end if
        else
            repeat with addr in addrs
                if (addr as string) is targetEmail then
                    tell acct to set default message signature to foundSig
                    set bound to true
                    exit repeat
                end if
            end repeat
        end if
    end repeat

    if bound then
        return "OK"
    else
        set allAddrs to {}
        repeat with acct in accounts
            repeat with addr in (email addresses of acct)
                set end of allAddrs to (addr as string)
            end repeat
        end repeat
        return "ACCOUNT_NOT_FOUND – bekannte Adressen: " & (allAddrs as text)
    end if
end tell
ASEOF

    local exit_code=$?
    local as_out as_err
    as_out=$(cat "$tmp_out"); as_err=$(cat "$tmp_err")
    rm -f "$tmp_out" "$tmp_err"

    if [ $exit_code -eq 0 ] && [ "$as_out" = "OK" ]; then
        log "  ✓ AppleScript: $account_email zugewiesen"
        return 0
    fi

    log "  AppleScript-Fehler (code=$exit_code): $as_out $as_err"

    # Fallback: Direkte Plist-Bindung (kein AppleScript/PPPC benötigt)
    bind_account_plist "$account_email" "$sig_uuid" && return 0

    log "  HINWEIS: PPPC-Profil deployen (Deployment-Seite > PPPC herunterladen + in Jamf einspielen)"
    log "           Danach Script erneut ausführen."
    return 1
}

# ---- Direkte Plist-Bindung (Fallback, kein AppleScript) ---------------------
bind_account_plist() {
    local account_email="$1"
    local sig_uuid="$2"

    # Mail Preferences Pfad (Sandbox zuerst, dann klassisch)
    local mail_pref=""
    for p in \
        "$USER_HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist" \
        "$USER_HOME/Library/Preferences/com.apple.mail.plist"; do
        [ -f "$p" ] && mail_pref="$p" && break
    done
    if [ -z "$mail_pref" ]; then
        # Plist noch nicht vorhanden — im Container anlegen
        mail_pref="$USER_HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist"
        $run_as mkdir -p "$(dirname "$mail_pref")" 2>/dev/null || true
        $run_as "$PLISTBUDDY" -c "Add :PerAccountDefaultSignatures dict" "$mail_pref" 2>/dev/null || true
        [ ! -f "$mail_pref" ] && { log "  Plist-Fallback: Plist kann nicht erstellt werden"; return 1; }
        log "  Plist-Fallback: Plist neu erstellt"
    fi

    # Account-UUID ermitteln — drei Quellen werden versucht
    local acct_uuid=""

    # Quelle 0: AppleScript-ID (read-only, kein PPPC — vorher via build_acct_id_map geladen)
    if [ -z "$acct_uuid" ]; then
        acct_uuid=$(acct_id_for_email "$account_email")
        [ -n "$acct_uuid" ] && log "  Plist-Fallback: Account-UUID aus Mail-ID: $acct_uuid"
    fi

    # Quelle 1: Mail V10-Verzeichnisstruktur (kein FDA nötig, macOS Sonoma/Sequoia)
    # Die UUID-Ordner unter dem V10-Verzeichnis entsprechen den Account-Identifiers,
    # die Mail auch als Schlüssel in PerAccountDefaultSignatures verwendet.
    local mail_ver_dir
    mail_ver_dir="$(dirname "$(dirname "$SIG_DIR")")"
    while IFS= read -r dir; do
        local base
        base=$(basename "$dir")
        if [[ "$base" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]]; then
            while IFS= read -r plist; do
                local found_email=""
                found_email=$("$PLISTBUDDY" -c "Print :AccountEmail" "$plist" 2>/dev/null || true)
                [ -z "$found_email" ] && found_email=$("$PLISTBUDDY" -c "Print :Email"    "$plist" 2>/dev/null || true)
                [ -z "$found_email" ] && found_email=$("$PLISTBUDDY" -c "Print :username" "$plist" 2>/dev/null || true)
                if [[ "$(echo "$found_email" | tr '[:upper:]' '[:lower:]')" == "$account_email" ]]; then
                    acct_uuid="$base"
                    break 2
                fi
            done < <(find "$dir" -maxdepth 2 -name "*.plist" 2>/dev/null)
        fi
    done < <(find "$mail_ver_dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

    if [ -n "$acct_uuid" ]; then
        log "  Plist-Fallback: Account-UUID aus Mail-Verzeichnis: $acct_uuid"
    fi

    # Quelle 2: Accounts4.db (braucht FDA, funktioniert auf älteren macOS-Versionen)
    if [ -z "$acct_uuid" ]; then
        local db="$USER_HOME/Library/Accounts/Accounts4.db"
        if [ -f "$db" ]; then
            acct_uuid=$(sqlite3 "$db" \
                "SELECT ZUUID FROM ZACCOUNT WHERE lower(ZUSERNAME) = lower('$account_email') LIMIT 1" \
                2>/dev/null)
            if [ -n "$acct_uuid" ]; then
                log "  Plist-Fallback: Account-UUID aus Accounts4.db: $acct_uuid"
            else
                log "  Plist-Fallback: Kein UUID für $account_email in Accounts4.db"
            fi
        else
            log "  Plist-Fallback: Accounts4.db nicht gefunden"
        fi
    fi

    if [ -z "$acct_uuid" ]; then
        log "  Plist-Fallback: Keine Account-UUID gefunden"
        return 1
    fi

    # PerAccountDefaultSignatures: flaches Dict accountUUID → signatureUUID (String)
    local keypath=":PerAccountDefaultSignatures:${acct_uuid}"

    # Sicherstellen dass PerAccountDefaultSignatures-Dict existiert
    $run_as "$PLISTBUDDY" -c "Add :PerAccountDefaultSignatures dict" "$mail_pref" 2>/dev/null || true

    local written=0
    # Bestehenden Eintrag updaten oder neu anlegen
    if $run_as "$PLISTBUDDY" -c "Set ${keypath} ${sig_uuid}" "$mail_pref" 2>/dev/null; then
        written=1
    elif $run_as "$PLISTBUDDY" -c "Add ${keypath} string ${sig_uuid}" "$mail_pref" 2>/dev/null; then
        written=1
    fi

    if [ $written -eq 1 ]; then
        log "  ✓ Plist-Bindung gesetzt: $account_email → $sig_uuid"
    else
        log "  Plist-Fallback fehlgeschlagen"
        return 1
    fi

    # accountsmap.plist: Signatur-UUID dem Account-Signatures-Array hinzufügen.
    # Mail ignoriert PerAccountDefaultSignatures wenn der Account in accountsmap.plist
    # kein Signatures-Array-Eintrag hat.
    local acct_map="$SIG_DIR/accountsmap.plist"
    if [ -n "$acct_uuid" ] && [ -f "$acct_map" ]; then
        # Bestehendes Array leeren und unsere Signatur eintragen
        $run_as "$PLISTBUDDY" -c "Delete :${acct_uuid}:Signatures" "$acct_map" 2>/dev/null || true
        $run_as "$PLISTBUDDY" -c "Add :${acct_uuid}:Signatures array" "$acct_map" 2>/dev/null || true
        if $run_as "$PLISTBUDDY" -c "Add :${acct_uuid}:Signatures:0 string ${sig_uuid}" "$acct_map" 2>/dev/null; then
            log "  accountsmap: Signatur zugewiesen ($account_email)"
        else
            log "  accountsmap: Fehler beim Schreiben für $account_email"
        fi
    elif [ -n "$acct_uuid" ]; then
        log "  accountsmap: Datei nicht gefunden ($acct_map)"
    fi

    return 0
}

# ---- accountsmap.plist mit ALLEN Signaturen eines Accounts aktualisieren ----
# Wird in Phase 3 aufgerufen (nach Mail-Exit), damit Mail die Änderungen beim
# nächsten Start sieht und nicht vorher überschreibt.
update_accountsmap_all() {
    local account_email="$1"
    shift
    local n_sigs=$#
    [ "$n_sigs" -eq 0 ] && return 0
    local sig_uuids=("$@")

    local acct_map="$SIG_DIR/accountsmap.plist"

    # Datei anlegen falls noch nicht vorhanden
    if [ ! -f "$acct_map" ]; then
        $run_as "$PLISTBUDDY" -c "Add : dict" "$acct_map" 2>/dev/null || true
        if [ ! -f "$acct_map" ]; then
            log "  accountsmap: Datei kann nicht erstellt werden — übersprungen"
            return 1
        fi
        log "  accountsmap: Datei neu erstellt"
    fi

    local acct_uuid=""

    # Quelle 1: AppleScript-ID (aus build_acct_id_map)
    acct_uuid=$(acct_id_for_email "$account_email")
    [ -n "$acct_uuid" ] && log "  accountsmap: UUID via AppleScript: $acct_uuid"

    # Quelle 2: Mail V10-Verzeichnis — läuft immer (gleiche Logik wie bind_account_plist)
    local mail_ver_dir
    mail_ver_dir="$(dirname "$(dirname "$SIG_DIR")")"
    while IFS= read -r dir; do
        local base
        base=$(basename "$dir")
        if [[ "$base" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]]; then
            while IFS= read -r plist; do
                local found_email=""
                found_email=$("$PLISTBUDDY" -c "Print :AccountEmail" "$plist" 2>/dev/null || true)
                [ -z "$found_email" ] && found_email=$("$PLISTBUDDY" -c "Print :Email"    "$plist" 2>/dev/null || true)
                [ -z "$found_email" ] && found_email=$("$PLISTBUDDY" -c "Print :username" "$plist" 2>/dev/null || true)
                if [[ "$(echo "$found_email" | tr '[:upper:]' '[:lower:]')" == "$account_email" ]]; then
                    acct_uuid="$base"
                    log "  accountsmap: UUID via V10-Verzeichnis: $acct_uuid"
                    break 2
                fi
            done < <(find "$dir" -maxdepth 2 -name "*.plist" 2>/dev/null)
        fi
    done < <(find "$mail_ver_dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

    # Quelle 3: Accounts4.db (Fallback)
    if [ -z "$acct_uuid" ]; then
        local db="$USER_HOME/Library/Accounts/Accounts4.db"
        if [ -f "$db" ]; then
            acct_uuid=$(sqlite3 "$db" \
                "SELECT ZUUID FROM ZACCOUNT WHERE lower(ZUSERNAME) = lower('$account_email') LIMIT 1" \
                2>/dev/null || true)
            [ -n "$acct_uuid" ] && log "  accountsmap: UUID via Accounts4.db: $acct_uuid"
        fi
    fi

    if [ -z "$acct_uuid" ]; then
        log "  accountsmap: Keine UUID für $account_email gefunden — übersprungen"
        return 0
    fi

    # Signatures-Array neu aufbauen mit allen UUIDs (primary zuerst)
    $run_as "$PLISTBUDDY" -c "Delete :${acct_uuid}:Signatures" "$acct_map" 2>/dev/null || true
    $run_as "$PLISTBUDDY" -c "Add :${acct_uuid}:Signatures array" "$acct_map" 2>/dev/null || true
    local idx=0
    for uuid in "${sig_uuids[@]}"; do
        $run_as "$PLISTBUDDY" -c "Add :${acct_uuid}:Signatures:${idx} string ${uuid}" "$acct_map" 2>/dev/null || true
        idx=$((idx + 1))
    done
    log "  ✓ accountsmap: ${n_sigs} Signatur(en) für $account_email eingetragen"
}

# ---- Account-IDs via AppleScript laden (read-only, kein PPPC nötig) --------
# Mail muss laufen. Setzt die globale Variable ACCT_ID_MAP mit "email|uuid"-Zeilen.
build_acct_id_map() {
    if ! pgrep -xq "Mail" 2>/dev/null; then return; fi
    local result
    result=$($run_as osascript 2>/dev/null << 'ASEOF'
tell application "Mail"
    set out to ""
    repeat with a in accounts
        set addrs to email addresses of a
        set aid to id of a as string
        if class of addrs is string then
            set out to out & (addrs as string) & "|" & aid & linefeed
        else
            repeat with addr in addrs
                set out to out & (addr as string) & "|" & aid & linefeed
            end repeat
        end if
    end repeat
    return out
end tell
ASEOF
    )
    if [ -n "$result" ]; then
        ACCT_ID_MAP="$result"
        log "  Account-IDs geladen: $(echo "$result" | grep -c '|') Einträge"
    fi
}

acct_id_for_email() {
    echo "$ACCT_ID_MAP" | grep -i "^${1}|" | cut -d'|' -f2 | head -1 | tr -d '[:space:]'
}

# ---- Hauptlogik -------------------------------------------------------------
if [ -n "$FORCE_EMAIL" ]; then
    ACCOUNTS="$FORCE_EMAIL"
    log "Test-Modus: Account manuell gesetzt auf $FORCE_EMAIL"
else
    ACCOUNTS=$(get_accounts)
fi

if [ -z "$ACCOUNTS" ]; then
    log "FEHLER: Keine Mail-Accounts gefunden."
    log "Tipp: Terminal braucht 'Vollständiger Festplattenzugriff' für manuellen Test."
    log "      Oder Script mit -e email@domain.com aufrufen."
    exit 1
fi
log "Gefundene Accounts: $(echo "$ACCOUNTS" | tr '\n' ' ')"

# Account-IDs laden während Mail noch läuft (read-only AppleScript, kein PPPC)
build_acct_id_map

# ---- Phase 1: Mail schliessen, Dateien schreiben ----------------------------
MAIL_WAS_RUNNING=0
if pgrep -xq "Mail" 2>/dev/null; then
    MAIL_WAS_RUNNING=1
    log "Mail wird kurz beendet..."
    $run_as osascript -e 'quit app "Mail"' 2>/dev/null || true
    sleep 3
fi

DEPLOYED=0
declare -a BOUND_ACCOUNTS=()
declare -a BOUND_NAMES=()
declare -a BOUND_UUIDS=()
declare -a ALL_SIG_PAIRS=()   # "email TAB uuid" für jede deployed Signatur (Phase-3-accountsmap)

while IFS= read -r ACCOUNT; do
    [ -z "$ACCOUNT" ] && continue

    # Alle Signaturen für diesen Account vom Server holen (JSON-Liste)
    LIST_TMP=$(mktemp /tmp/siglist_XXXXXX)
    chmod a+r "$LIST_TMP" 2>/dev/null || true

    LIST_HTTP=$(curl -s \
        --connect-timeout 10 \
        --max-time 30 \
        -H "X-Api-Key: $API_KEY" \
        -w "%{http_code}" \
        -o "$LIST_TMP" \
        "$SERVER_URL/api/mailsignatures-list/$ACCOUNT" 2>/dev/null || echo "000")

    if [ "$LIST_HTTP" != "200" ]; then
        log "Keine Signatur für $ACCOUNT (HTTP $LIST_HTTP)"
        rm -f "$LIST_TMP"
        continue
    fi

    # Format: eine Zeile pro Signatur, TAB-getrennt: uuid <TAB> base64name
    # Kein Python nötig — reines bash + base64 (macOS built-in)
    IS_PRIMARY=1
    while IFS=$'\t' read -r SIG_UUID SIG_NAME_B64; do
        [ -z "$SIG_UUID" ] && continue
        SIG_NAME=$(printf '%s' "$SIG_NAME_B64" | base64 -D 2>/dev/null || echo "$ACCOUNT")

        SIG_TMP=$(mktemp /tmp/sigfile_XXXXXX)
        chmod a+r "$SIG_TMP" 2>/dev/null || true

        HTTP_CODE=$(curl -s \
            --connect-timeout 10 \
            --max-time 30 \
            -H "X-Api-Key: $API_KEY" \
            -w "%{http_code}" \
            -o "$SIG_TMP" \
            "$SERVER_URL/api/mailsignature-by-uuid/$SIG_UUID" 2>/dev/null || echo "000")

        if [ "$HTTP_CODE" != "200" ]; then
            log "  Fehler beim Download: $SIG_NAME (HTTP $HTTP_CODE)"
            rm -f "$SIG_TMP"
            continue
        fi

        log "Deploying: $ACCOUNT  →  $SIG_NAME"
        write_signature_file "$SIG_UUID" "$SIG_NAME" "$SIG_TMP"
        ALL_SIG_PAIRS+=("${ACCOUNT}	${SIG_UUID}")

        if [ "$IS_PRIMARY" -eq 1 ]; then
            # Erste Signatur = Standard-Signatur (auto-insert), Plist-Bindung setzen
            bind_account_plist "$ACCOUNT" "$SIG_UUID"
            BOUND_ACCOUNTS+=("$ACCOUNT")
            BOUND_NAMES+=("$SIG_NAME")
            BOUND_UUIDS+=("$SIG_UUID")
            IS_PRIMARY=0
        fi

        DEPLOYED=$((DEPLOYED + 1))
        rm -f "$SIG_TMP"
    done < "$LIST_TMP"

    rm -f "$LIST_TMP"
done <<< "$ACCOUNTS"

log "Signaturdateien geschrieben: $DEPLOYED"

# ---- Phase 2: Mail öffnen, Accounts zuweisen (AppleScript mit PPPC) ----------
if [ "$DEPLOYED" -gt 0 ]; then
    log "Mail wird gestartet um Accounts zuzuweisen..."
    $run_as open -a Mail
    WAITED=0
    while ! pgrep -xq "Mail" 2>/dev/null && [ $WAITED -lt 20 ]; do
        sleep 1; WAITED=$((WAITED + 1))
    done
    sleep 5  # Mail Zeit geben sein AppleScript-Dictionary zu registrieren

    for i in "${!BOUND_ACCOUNTS[@]}"; do
        bind_account "${BOUND_ACCOUNTS[$i]}" "${BOUND_NAMES[$i]}" "${BOUND_UUIDS[$i]}"
    done
fi

# Mail schliessen (immer) damit Phase 3 die Preferences korrekt setzen kann
if pgrep -xq "Mail" 2>/dev/null; then
    log "Mail wird beendet (für Preferences-Update)..."
    $run_as osascript -e 'quit app "Mail"' 2>/dev/null || true
    sleep 3  # Warten bis Mail seine Preferences gespeichert hat
fi

# ---- Phase 3: Standard-Signaturen via defaults setzen (nach Mail-Exit) ------
# Drei Keys müssen gesetzt werden damit Mail die Signatur automatisch einfügt:
#   PerAccountDefaultSignatures  – legacy, accountUUID → signatureUUID
#   SignaturesSelected           – primärer Key für Auto-Insert, accountUUID → signatureUUID
#   SignatureSelectionMethods    – Modus, accountUUID → "SelectedOnly"
# Alle drei im Container-Pfad (nicht in ~/Library/Preferences — Mail ist sandboxed).
if [ "$DEPLOYED" -gt 0 ]; then
    MAIL_CONTAINER_PREF="$USER_HOME/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail"

    # PerAccountDefaultSignatures komplett neu aufbauen
    $run_as defaults delete "$MAIL_CONTAINER_PREF" PerAccountDefaultSignatures 2>/dev/null || true

    PHASE3_COUNT=0
    for i in "${!BOUND_ACCOUNTS[@]}"; do
        ACCT_UUID_3=$(acct_id_for_email "${BOUND_ACCOUNTS[$i]}")
        [ -z "$ACCT_UUID_3" ] && continue
        SIG_UUID_3="${BOUND_UUIDS[$i]}"

        PHASE3_OK=0

        # 1) PerAccountDefaultSignatures
        if $run_as defaults write "$MAIL_CONTAINER_PREF" PerAccountDefaultSignatures \
            -dict-add "$ACCT_UUID_3" "$SIG_UUID_3" 2>/dev/null; then
            PHASE3_OK=1
        fi

        # 2) SignaturesSelected — der Key, den Mail tatsächlich für Auto-Insert nutzt.
        #    Enthält auch Mailbox-UUIDs, daher nicht löschen, nur -dict-add.
        $run_as defaults write "$MAIL_CONTAINER_PREF" SignaturesSelected \
            -dict-add "$ACCT_UUID_3" "$SIG_UUID_3" 2>/dev/null || true

        # 3) SignatureSelectionMethods — muss "SelectedOnly" sein (nicht random/sequential)
        $run_as defaults write "$MAIL_CONTAINER_PREF" SignatureSelectionMethods \
            -dict-add "$ACCT_UUID_3" "SelectedOnly" 2>/dev/null || true

        if [ "$PHASE3_OK" -eq 1 ]; then
            log "  ✓ Standard-Signatur: ${BOUND_ACCOUNTS[$i]}"
            PHASE3_COUNT=$((PHASE3_COUNT + 1))
        else
            log "  ✗ Fehler Standard-Signatur: ${BOUND_ACCOUNTS[$i]}"
        fi
    done
    log "Standard-Signaturen gesetzt: $PHASE3_COUNT (PerAccountDefaultSignatures + SignaturesSelected + SignatureSelectionMethods)"

    # Phase 3b: accountsmap.plist für Accounts mit mehreren Signaturen aktualisieren
    # Läuft nach Mail-Exit — Mail überschreibt unsere Änderungen nicht mehr.
    for acct_email in "${BOUND_ACCOUNTS[@]}"; do
        UUIDS_FOR_ACCT=()
        for pair in "${ALL_SIG_PAIRS[@]}"; do
            p_email="${pair%	*}"
            p_uuid="${pair##*	}"
            [ "$p_email" = "$acct_email" ] && UUIDS_FOR_ACCT+=("$p_uuid")
        done
        SIG_COUNT_ACCT=0
        for _u in "${UUIDS_FOR_ACCT[@]}"; do SIG_COUNT_ACCT=$((SIG_COUNT_ACCT+1)); done
        [ "$SIG_COUNT_ACCT" -le 1 ] && continue
        log "  accountsmap Phase3: $acct_email — $SIG_COUNT_ACCT Signaturen"
        update_accountsmap_all "$acct_email" "${UUIDS_FOR_ACCT[@]}"
    done
fi

# ---- Mail neu starten damit Signaturen ohne manuellen Neustart aktiv sind ----
if [ "$DEPLOYED" -gt 0 ]; then
    # Sicherstellen dass Mail beendet ist bevor wir es neu öffnen
    if pgrep -xq "Mail" 2>/dev/null; then
        log "Mail wird beendet für Neustart..."
        $run_as osascript -e 'quit app "Mail"' 2>/dev/null || true
        sleep 3
    fi
    log "Mail wird neu gestartet..."
    $run_as open -a Mail
    WAITED=0
    while ! pgrep -xq "Mail" 2>/dev/null && [ $WAITED -lt 20 ]; do
        sleep 1; WAITED=$((WAITED + 1))
    done
    log "Mail neu gestartet — Signaturen aktiv."
fi

log "Fertig — $DEPLOYED Signaturen deployed."
